// Generated by https://quicktype.io

namespace ElearningDemo.Models.Options
{
    public partial class CoursesOptions
    {
        public int PerPagina { get; set; }

        public CoursesOrderOptions Order { get; set; }
    }

    public partial class CoursesOrderOptions
    {
        public string By { get; set; }

        public bool Ascending { get; set; }

        public string[] Allow { get; set; }
    }
}